on:
  push:
    paths:
      - '**'
      - "!**.md"
  pull_request:
    paths:
      - '**'
      - "!**.md"
name: Benchmark
jobs:
  compare:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.version }}
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Run Benchmark
        run: set -o pipefail; go test ./... -benchmem -run=^$ -bench . | tee output.txt
      - name: Get Previous Benchmark Results
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Save Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1.16.2
        with:
          tool: 'go'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: 'benchmarks'
          fail-on-alert: true
          comment-on-alert: true
          auto-push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          save-data-file: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
